### ISSUE TITLE
Bounds check

### ISSUE THREAD

**Issue by guycalledfrank** [ands/seamoptimizer#1]
Just testing the library :)
Found it crashing with Y coordinate being 1024 for a 1024 map (shouldn't be > 1023). Maybe my fault, but also maybe there needs to be something like min(ax+1, w-1) and so on here:
https://github.com/ands/seamoptimizer/blob/master/seamoptimizer.h#L484

**Comment by ands** [comment]
Yeah, the border conditions need some clean up... :)
